### ISSUE TITLE
Support to run as administrator

### ISSUE THREAD

**Issue by singhrasster** [hymkor/expect#10]
When using this script to run my binary/exe that asks for series of questions, and need administrator privileges, is it possible to execute this without prompting the user for admin privilege? Can this silently run everything as admin?

**Comment by hymkor** [comment]
`expect.exe` can not hit the buttons on the UAC dialog. So, for your purpose, we have to run `expect.exe`  with administrator privileges from the beginning like this.

**foo.cmd**
```
@powershell "Start-Process -FilePath '%USERPROFILE%\Share\bin64\expect.exe' -ArgumentList '%~dpnx0' -verb runas"
@exit /b

echo(true)
spawn("CMD.EXE")
expect([[C:\Users\]])
sendln([[mkdir "%windir%\dummy"]])
expect([[C:\Users\]])
sendln("pause")
expect([[C:\Users\]])
sendln([[rmdir "%windir%\dummy"]])
sendln("pause")

-- vim:set ft=lua:
```

**Caution**: the previous version of `expect.exe` has a bug that scripts embeded in batchfile could not be executed sometimes. If you uses batchfile-embeded-scripts, I recommend updating to the version  
[20181218](https://github.com/zetamatta/expect/releases/tag/20181218)

**Comment by singhrasster** [comment]
@zetamatta Thanks for your response. I tried what you suggested and its still showing the prompt when I try to run the .cmd file:

Do you want to allow the following program from an unknown publisher to make changes to this computer?
Program name: Unknown
Publisher: unknown
File origin: hard drive on this computer

**Comment by hymkor** [comment]
Any applications can not erase the prompt on the default Windows settings.
(If it is possible, your OS has a security hole)

If you want to remove it, you have to disable "User Account Control" by running `useraccountcontrolsettings.exe`
