### ISSUE TITLE
Support to log the output/errors to a file when running lua script

### ISSUE THREAD

**Issue by singhrasster** [hymkor/expect#11]
Does this package support a way to log information to a file ?
My CLI app has a series of questions and answers and there are questions for which, if validation fails for the input provided, it asks the same question again after stating that "validation failed". So, my program does not exit in this case, but just reprompts with the same question, till the user has provided a valid answer. If I would like to add all these outputs/errors  (like 'validation failed') and also any other information to a log file, is it something I can do from my .lua file? For example, following the readme, lets say I create a sample.lua file and run it against my .exe (Go CLI app) as "expect.exe sample.lua",

echo(true)
if spawn([[C:\test.exe]]) then
    expect("Enter username")
    echo(true)
    send("xxx\r")
    ....
    ....
    ....
end

Lets say xxx was an invalid input and my CLI app prints fmt.print("Invalid value")
and then prompt same question to the user to re-enter the value,
Is there a way I can log this message and infact all the interactions to a file (including all the stdout/fmt I see as output from my CLI app) from this .lua file or something?

**Comment by hymkor** [comment]
> Does this package support a way to log information to a file ?

No,  `expect.exe` does not record all output. It only reads the line where the cursor exists on the console buffer.

Is it impossible for `expect` function to wait for both a successful message and a failed message ?

```lua
while true do
  send("xxx\r")
  rc = expect("SUCESSMESSAGE","Invalid value")
  if rc == 0 do
    break
  end
  -- retry action ---
end
-- success action --
```
