### ISSUE TITLE
How to insert date/time into script?

### ISSUE THREAD

**Issue by IzualYang** [hymkor/expect#13]
Looks like the only way is to generate a lua script from my batch script

**Comment by IzualYang** [comment]
I think this is a common scenario, because if you are looking for sth like Expect, you must be scheduling configuration backups of network devices.

**Comment by hymkor** [comment]
<DEL>Is</DEL> <INS>Does</INS> this satisfy your needs ?

```
sendln("echo " ..  os.date("%Y/%m/%d %H:%M:%S") )
```

**Comment by IzualYang** [comment]
Great! I've totally ~~forgot~~ forgotten that it is a lua script.
I also didn't notice the arg[], which partly meets my needs

**Comment by hymkor** [comment]
Can I close this issue ? > @IzualYang

**Comment by IzualYang** [comment]
Yes, of course
