### ISSUE TITLE
Any other way of simulating the Enter key?

### ISSUE THREAD

**Issue by vctls** [hymkor/expect#14]
I'm trying to use this with Bitvise's `stnlc` ssh client, but `\r` and `\n` are just counted as regular characters and not as pressing the Enter key.
Are there any other ways of confirming your input?

**Comment by hymkor** [comment]
The reason that Bitvise's stnlc ssh client could not recieve Enter-key may be expect.exe's bug.
I try to fix it.

**Comment by vctls** [comment]
Oh... I was wondering if pressing Enter in `cmd` was actually interpreted as something more than a carriage return. Could it be possible that the program expects some other signal?
I asked Bitvise if there was anything particular with their program. I'm waiting for their answer.

**Comment by hymkor** [comment]
My library go-console which is called in expect.exe, uses the API [WriteConsoleInput](https://docs.microsoft.com/en-us/windows/console/writeconsoleinput) to send key-events, but it did not set the parameter `wRepeatCount` in [KEY_EVENT_RECORD](https://docs.microsoft.com/en-us/windows/console/key-event-record-str). It should set it `1` (but it was `0`).

It is possible that CMD.EXE ignored `wRepeatCount` and  `Bitvise's stnlc ssh client` read and used it in [ReadConsoleInput](https://docs.microsoft.com/en-us/windows/console/readconsoleinput)

**Comment by hymkor** [comment]
Would you test the [new version (20191220)](https://github.com/zetamatta/expect/releases/tag/20191220) ? To send Enter-key, call `send("\r")` or `sendln("")`

**Comment by vctls** [comment]
I'm getting an error with the new amd64 exe:
```
λ expect test.lua
test.lua at EOF:   syntax error
```

**Comment by hymkor** [comment]
Did you forget to close the double quotes?

**Comment by vctls** [comment]
I did not change my scripts at all. I even tried again with the example script on the Readme.

**Comment by vctls** [comment]
Oh, never mind, I got it. For some reason the program now wants my script to end with a new line.

**Comment by vctls** [comment]
It's working! 🎉 Thank you so much! 🙏

**Comment by hymkor** [comment]
That's good. I am glad that your problem is solved.

Thanks to your report, I was able to fix the bug. Thank you very much.
