### ISSUE TITLE
Distribution via Chocolatey

### ISSUE THREAD

**Issue by justmiles** [hymkor/expect#17]
Hello and thank you for this useful project.

Do you think there's any value in [distributing this project through Chocolatey](https://docs.chocolatey.org/en-us/create/create-packages)? The majority of tooling/packages like this that I install are provisioned via Chocolatey. I think other may benefit from it as well.

Thoughts?

**Comment by hymkor** [comment]
Thank you for using my software.

Your advice is right. I know Chocolatey as an useful installer(packaging system) on Windows.
 ( I do not use it, but I am using a similar software called [scoop](https://scoop.sh/)  )

But, I do not have enough time to do it myself now. Sorry.
