### ISSUE TITLE
`The handle is invalid.` is output when using in GitHub Actions PowerShell. 

### ISSUE THREAD

**Issue by trackpadpro** [hymkor/expect#25]
```
Run powershell -ExecutionPolicy ByPass -File .\\scripts\\exampleExpectLua.ps1 -STEAM_LOGIN_COOKIE ***
expect.lua v0.[6](https://github.com/trackpadpro/tppsss/runs/5965160218?check_suite_focus=true#step:6:6).2-6-g5[9](https://github.com/trackpadpro/tppsss/runs/5965160218?check_suite_focus=true#step:6:9)df0cc-windows-amd64
"D:\a\tppsss\tppsss\scripts\exampleExpectLua.ps1\..\exampleExpect.lua\..\..\tppsss.exe"
The handle is invalid.
The handle is invalid.
The handle is invalid.
The handle is invalid.
Unable to find steamLoginSecure. This cookie is used for fetching full item price history.
Would you like to set it? [y/n] Unrecognized command. The steamLoginSecure cookie can be set later using the "setup" command.
Online
Offline
```
^is the output
```
echo(true)
if spawn(arg[0]..[[\..\..\tppsss.exe]]) then
    timeout = 2
    RC = expect("[y/n]")
    timeout = 3600
    echo(false)
    if RC==0 then
        send("n\r")
    end
    expect("Online")
    send("setup\r")
    expect("cookie:")
    send(arg[1].."\r")
    expect("steamLoginSecure set")
    send("break\r")
end
```
^is called by `expect.exe $pathToScripts\..\exampleExpect.lua $STEAM_LOGIN_COOKIE`

Your program works very well for me in PowerShell on my own desktop, but in MSYS2 and in the GitHub runner PowerShell it outputs this error 4 times. I am not sure if I am simply handling the arguments too poorly. Is PowerShell not similar enough to Command Prompt? I guess I may be able to just build in MSYS and use the other Expect, but I really like using yours on my own computer and wanted to simulate the testing on actions, so I would greatly appreciate it if you could take a look at if I am using your program wrong or if it is easily fixable!

This is kind of similar to #12 maybe. Below are some links that involve what I think possible causes are, but I have never used Go or any of these libraries, so I have trouble understanding if it is indeed the cause in expect.lua. 

https://github.com/moby/moby/issues/15272
https://github.com/moby/moby/pull/17738
https://github.com/golang/go/issues/11914

Thanks!

**Comment by hymkor** [comment]
@trackpadpro 

Thank you for reporting.
`The handle is invalid` is the error message when Expect.lua failed to call the Windows classic console API.

Expect.lua calls GetConsoleScreenBufferInfo which is one of the classic console API instead of reading the standard output from the process started by spawn function like linux's expect tools. This API works only on the Windows classic console or its compatible terminal (Command-Prompt, WindowsTerminal, WezTerm and so on) .

I suspect MSYS2 and GitHub runner PowerShell do not have compatiblity with the Windows classic console.
If it is right, sorry, the current version of Expect.lua can not work under them.

**Comment by trackpadpro** [comment]
Thank you for your explanation. 

Do you plan on trying to expand compatibility or should I just close the issue? I guess I will look for a way for a GitHub runner to open a compatible terminal.

**Comment by hymkor** [comment]
Sorry, it is probably difficult for me to support other terminals. Would you please close this issue ?

**Comment by trackpadpro** [comment]
No problem!
