### ISSUE TITLE
loop condition for expect

### ISSUE THREAD

**Issue by azizgokhannarin** [hymkor/expect#26]
After a few certain expections, I need conditional expect for send something. But I could not deal with it. 

Also is it possible to read console output?

**Comment by hymkor** [comment]
The current `expect("PATTERN1","PATTERN2",...)` function can only return the number which pattern is matched

Is what you mean that you want to get the console output which is matched ?

If it is right, it is impossible now. However, I can expand the specification as your request .

For example, If you wrote the script as `local rc,lines = expect2("PATTERN1","PATTERN2",...)` , you would get the console lines with the variable `lines`.  Can this feature satisfy your needs?

**Comment by azizgokhannarin** [comment]
Thank you for your quick response.

I try to connect automatically for OpenVPN. If session is terminated internal by myself or external by admin, I just got signal messages such as SIGTERM or SIGUSR1, etc. That time, expect process stays on suspended mode. However I want to it get terminated.

> echo(true)
> 
> PID=spawn ([[C:\Program Files\OpenVPN\bin\openvpn.exe ]],etc...)
> expect("Enter Auth Username:")
> 
> while true do
> 	send(arg[1])
> 	send("\r")
> 	expect("Enter Auth Password:")
> 	send(arg[2])
> 	send("\r")
> 	expect("token Password:")
> 	send(arg[3])
> 	send("\r")
> 	status=expect("Enter Auth Username:","SIGTERM","SIGUSR1")
> 	
> 	if (status == 1 or status == 2) then
>             kill(PID)
> 		break
> 	end
> end
> 
> os.exit(1)
>

**Comment by azizgokhannarin** [comment]
At last!

I did it like this:

```
while true do
	timeout=2592000
	status=expect("Enter Auth Username:", "Enter Auth Password:", "token Password:", "SIGTERM")
	
	if(status==0) then
		sendln(arg[1])
	end
	
	if(status==1) then
		sendln(arg[2])
	end
	
	if(status==2) then
		sendln(arg[3])
	end
	
	if(status<0 or status==3) then
		kill(PID)
		break
	end
end
```
In one way SIGTERM console output can be catched by expect method, exclusive other signals.

Other important issue is, expect is admitted as dangerous code for antivirus software. What can be done about this issue?

**Comment by hymkor** [comment]
> Other important issue is, expect is admitted as dangerous code for antivirus software. What can be done about this issue?

I can do nothing for antivirus software behaviour .
