### ISSUE TITLE
Capture output from program into LUA varaible? 

### ISSUE THREAD

**Issue by rdrdrdrd95** [hymkor/expect#30]
First of all this is great! Fantastic work. 

I want to replicate this functionality in TCL Expect: 

```TCL
#first step is to query the count from the program to build a loop count
#we use the -re tag to capture the site count from the output buffer after the token "Count: " and extend to the end of the whole output
expect $prompt
send -- "get_count\n"
expect -re {Count: (.*)\n.*}

set count $expect_out(1,string)
sleep 1
#sleeps are just to ensure we dont over-run the CLI

#we do not need to expect here since it was part of the last regex
#now we configure the output path
send -- "set_log_path $log_path\n"
```

Is this currently possible in the go implementation? 

Thanks!

**Comment by hymkor** [comment]
> Is this currently possible in the go implementation?

No, it can not yet, now.

I would like to implement the feature capturing output someday.

**Comment by rdrdrdrd95** [comment]
If you make the CONOUT$ buffer available to the LUA as a global this would be fairly trivial to process.

**Comment by hymkor** [comment]
On v0.8.0, Implement the `shot(N)` function to capture the N-lines of the console buffer.
