### ISSUE TITLE
How use another port in ssh?

### ISSUE THREAD

**Issue by 9Demien9** [hymkor/expect#32]
Hello! 
You did a great thing! Thanks. 
I turn to your example.
But I can't use an alternative **ssh** port. 
Perhaps you can give an example of how to do this. If you do not specify the port, everything works.

Thank you in advance!

**Comment by hymkor** [comment]
OK. I quoted the line calling ssh.exe from my Lua script.

``` lua
local SSHEXEPATH=os.getenv("windir") .. [[\system32\OpenSSH\ssh.exe]]
local remoteid = arg[1]
spawnctx(SSHEXEPATH,
    "-o","ServerAliveInterval=60",
    "-N",
    "-v",
    "-o","PubkeyAcceptedKeyTypes=+ssh-dss",
    "-p","27311",
    "-L","13333:"..remoteip..":3389",
    "hymkor@example.com")
```

Can it satisfy your needs ?

**Comment by 9Demien9** [comment]
> ```lua
> spawnctx
> ```

How do you call expect directly from lua?

**Comment by hymkor** [comment]
`spawnctx(NAME,ARG1,ARG2,...)` is a new built-in function available since v0.5.0
It is similar with spawn() but the process started by spawnctx is killed automatically when Ctrl-C is pressed.

To specify the port for ssh.exe , would you set the parameter as below to spawn() or spawnctx() ?

``` lua
"-p","27311",
```

**Comment by 9Demien9** [comment]
> `spawnctx(NAME,ARG1,ARG2,...)` is a new built-in function available since v0.5.0 It is similar with spawn() but the process started by spawnctx is killed automatically when Ctrl-C is pressed.
> 
> To specify the port for ssh.exe , would you set the parameter as below to spawn() or spawnctx() ?
> 
> ```lua
> "-p","27311",
> ```

You don't quite understand me.

**Comment by 9Demien9** [comment]
> `spawnctx(NAME,ARG1,ARG2,...)` is a new built-in function available since v0.5.0 It is similar with spawn() but the process started by spawnctx is killed automatically when Ctrl-C is pressed.
> 
> To specify the port for ssh.exe , would you set the parameter as below to spawn() or spawnctx() ?
> 
> ```lua
> "-p","27311",
> ```

You don't quite understand me.
I am use expect as os.execute("expect.exe .....
How i can used expect directly in lua? 
require "?"

**Comment by hymkor** [comment]
There are no ways to import Expect.Lua on the pure lua interpreter.

Expect.Lua is a standalone application using Gopher-Lua engine.
It is not a library.
`spawn`, `spawnctx` and other extended functions are available only in the script **executed on expect.exe**.

**Comment by 9Demien9** [comment]
> There are no ways to import Expect.Lua on the pure lua interpreter.
> 
> Expect.Lua is a standalone application using Gopher-Lua engine. It is not a library. `spawn`, `spawnctx` and other extended functions are available only in the script **executed on expect.exe**.

Are you include expect.exe in lua?! But how?!

**Comment by hymkor** [comment]
The expect.exe contains the built-in Lua interpreter called as [GopherLua](https://github.com/yuin/gopher-lua) that is the golang library.
You do not have to use `require` statement.
You have to make your script using `spawn` function and so on, and call it by expect.exe like `expect.exe YOURSCRIPT.lua` .

**Comment by 9Demien9** [comment]
> Ожидаемый.exe содержит встроенный интерпретатор Lua, называемый [GopherLua](https://github.com/yuin/gopher-lua) , который является библиотекой golang. Вам не нужно использовать `require`оператор. Вы должны сделать свой скрипт, используя `spawn`функцию и т. д., и вызвать его с помощью expect.exe, например `expect.exe YOURSCRIPT.lua`.

Yes, thanks a lot, I figured it out. I originally used io.popen in lua, but it only works with os.execute.
