### ISSUE TITLE
Automatic logout happening?

### ISSUE THREAD

**Issue by klar-C** [hymkor/expect#33]
Hi,

First of all thanks for the great script.

I'm trying to use this script to automatically log into some servers (and then do work manually). It works fine with the provided script and command
`
.\expect sample.lua name@server password
`
however it automatically ends the session after around 15 seconds. Is this a setting I can change somewhere?

To note: I needed to copy the ssh.exe into the same folder because it was not able to find it through the windows path (even though it was there).

**Comment by hymkor** [comment]
Thank you for using my product.

If you uses bash as the login-shell, how about `sendln("export TMOUT=0")` after login ?

> To note: I needed to copy the ssh.exe into the same folder because it was not able to find it through the windows path (even though it was there).

Yes, I understand it is possible that ssh.exe may not exist in `C:\Windows\system32\OpenSSH`  not on Windows-11.

**Comment by klar-C** [comment]
Thanks for the quick response.

I'm using cmd from within Windows. Do you know what the corresponding way would be to set it from there?

When logging in normally through ssh directly I don't have the time-out issue.

Edit:

I tried running it through the bash mode of cmder but then your script crashes with the error (after prompting the password):
ERROR
Pseudo-terminal will not be allocated because stdin is not a terminal.

**Comment by hymkor** [comment]
You do not have to start expect.exe on bash. I wanted to know the shell used on the server (not client) where you were going to login with ssh .

Is the server that you try to login, Windows-Server or Linux Server ?

> however it automatically ends the session after around 15 seconds

Is it mean that ssh.exe called from Expect-lua terminates after around 15 seconds ?

If you use sample.lua, then did you remove the line: `sendln("exit")`  ?

**Comment by klar-C** [comment]
It is a Linux server yes. So I'm trying to ssh into a Linux server from a Windows cmd line without having to type the password each time. Apologies for the misunderstanding.

And yes, I'm able to log in and do stuff, but after 15 seconds it just ends the ssh session.

I took out the "sendln("exit")" line but that did not change anything.

Below the lua script I'm using (still with the line in it). It is exactly the same as in the documentation besides that I changed the ssh path.


if #arg < 2 then
    print("expect.exe sample.lua USERNAME@DOMAIN PASSWD")
    os.exit(0)
end
local account = arg[1]
local password = arg[2]
local sshexe = "E:/cmder/ssh.exe"

local sshpid = spawn(sshexe,"-p","22",account)
if not sshpid then
    print("ssh.exe is not found")
    os.exit(1)
end
timeout = 10
capturelines = 3 -- default is 2

while true do
    local rc = expect(
    "password:",
    "Are you sure you want to continue connecting (yes/no/[fingerprint])?",
    "Could not resolve hostname")
    if rc == 0 then
        **sendln(password)**
        rc = expect("~]$","Permission denied, please try again")
        if rc == 0 then
            sendln("exit")
        else
            kill(sshpid)
        end
        break
    elseif rc == 1 then
        sendln("yes")
        print() -- move cursor down not to capture same keyword
    elseif rc == -2 then
        echo("TIMEOUT")
        break
    elseif rc == -1 then
        echo("ERROR")
        break
    else
        echo(string.format("Error keyword found \"%s\". Exit",_MATCH))
        break
    end
end

**Comment by hymkor** [comment]
```
rc = expect("~]$","Permission denied, please try again")
```

It is possible that `expect` function could not find the prompt.

Would you please remove these red-painted lines?

``` diff
diff --git a/sample.lua b/sample.lua
index cf78ff8..04ef3b7 100644
--- a/sample.lua
+++ b/sample.lua
@@ -11,7 +11,6 @@ if not sshpid then
     print("ssh.exe is not found")
     os.exit(1)
 end
-timeout = 10
 capturelines = 3 -- default is 2
 
 while true do
@@ -22,12 +21,6 @@ while true do
 
     if rc == 0 then
         sendln(password)
-        rc = expect("~]$","Permission denied, please try again")
-        if rc == 0 then
-            sendln("exit")
-        else
-            kill(sshpid)
-        end
         break
     elseif rc == 1 then
         sendln("yes")
```

**Comment by klar-C** [comment]
That worked - thanks! Really appreciate the help.
