### ISSUE TITLE
Send Arrow Keys

### ISSUE THREAD

**Issue by chrisdonlan** [hymkor/expect#35]
Is it possible to send up/down arrow keys so that the cli getting automated can be navigated by arrow keys? 

If so, can you document how this would be done?

**Comment by hymkor** [comment]
Thank you for the question.

It was impossible until v0.10.0, therefore I have implemented a new function: `sendvkey(VIRTUAL_KEY_CODE)` on [v0.11.0].

Would you please try `sendvkey` of [v0.11.0] ?
( The sample code is written in [the release note of v0.11.0][v0.11.0] )

[v0.11.0]: https://github.com/hymkor/expect/releases/tag/v0.11.0

**Comment by hymkor** [comment]
@chrisdonlan ?

**Comment by hymkor** [comment]
Though I would close this issue, if you have a problem, please reopen it.
