### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by tangingw** [hymkor/expect#4]
Hi When I run expect.exe test.lua, I get the following error:
.\test.lua line:1(column:1) near '?': Invalid token

This is my `test.lua`, which is exactly your `sample.lua`
```lua
echo(true)
if spawn([[c:\Program Files\Git\usr\bin\ssh.exe]],"foo@example.com") then
    expect("password:")
    echo(false)
    send("PASSWORD\r")
    expect("~]$")
    echo(true)
    send("exit\r")
end
```

**Comment by hymkor** [comment]
The BOM may exist at the first line.
(BOM is the byte order mark for UTF8 and it is invisible but not white-space )

If you create test.lua with **notepad.exe** and save as **UTF8**, would you save as **ANSI** ?
(or please use other editor)

**Comment by tangingw** [comment]
Would utf-8 be the issue? I tried with notepad and vs code. Both throw the same error.



Sent from my ASUS

-------- Original Message --------

**Comment by tangingw** [comment]
Just tried with ASCII. This cannot run in utf-8



-------- Original Message --------

**Comment by hymkor** [comment]
Would you attach your test.lua as a file ?

**Comment by tangingw** [comment]
[
[test.lua.txt](https://github.com/zetamatta/expect/files/2265711/test.lua.txt)
Please remove the .txt

It works with ASCII, but not UTF-8.
](url)

**Comment by hymkor** [comment]
I see your `test.lua` with binary editor. The first 3 bytes EF BB BF occurs error. Remove them.

![image](https://user-images.githubusercontent.com/3752189/43765692-82d2fc04-9a6b-11e8-8065-f355e9954fc2.png)

**Comment by tangingw** [comment]
Thanks for the information.





-------- Original Message --------

**Comment by hymkor** [comment]
I will implement the code to skip EF BB BF from source Lua files. Please wait a few days.

**Comment by hymkor** [comment]
Done. See https://github.com/zetamatta/expect/releases/tag/20180807 to download binary executable.

**Comment by tangingw** [comment]
Thanks for all the modification.

I will test it later and provide necessary feedback

-------- Original Message --------
