### ISSUE TITLE
Command Line argument on lua

### ISSUE THREAD

**Issue by tangingw** [hymkor/expect#5]
Does it work like this?
```
expect.ext test.lua arg1 arg2 arg3
```

**Comment by hymkor** [comment]
Now it is not supported yet. But, I will implement it. Please wait.

**Comment by tangingw** [comment]
Please let me know when it is ready.



-------- Original Message --------

**Comment by hymkor** [comment]
In a few days. If you want as soon as possible, I can hurry.

**Comment by hymkor** [comment]
Done. See https://github.com/zetamatta/expect/releases/tag/20180807 to download binary executable.

**Comment by tangingw** [comment]
Thanks for the file. Will test it tomorrow.

**Comment by tangingw** [comment]
The argument works. Thanks

**Comment by Jan-E** [comment]
Nice feature. I am using this now as well. Just had to look up how string concatenation in lua .. works.
