### ISSUE TITLE
Segfault when using OpenSSH-Win64

### ISSUE THREAD

**Issue by Jan-E** [hymkor/expect#8]
Nice idea!

When I try to spawn the Win64 version of https://github.com/PowerShell/Win32-OpenSSH I am running into a crash:
```
D:\OpenSSH-Win64>expect expect.lua
runtime: VirtualAlloc of 1048576 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x598f21, 0xd)
        c:/go/src/runtime/panic.go:616 +0x88
runtime.sysMap(0xc3e4150000, 0x100000, 0x1, 0x69cd18)
        c:/go/src/runtime/mem_windows.go:122 +0x13b
runtime.(*mheap).sysAlloc(0x6842a0, 0x100000, 0x1f1337d0)
        c:/go/src/runtime/malloc.go:470 +0xdb
runtime.(*mheap).grow(0x6842a0, 0x1, 0x0)
        c:/go/src/runtime/mheap.go:907 +0x67
runtime.(*mheap).allocSpanLocked(0x6842a0, 0x1, 0x69cd28, 0x1f1337d0)
        c:/go/src/runtime/mheap.go:820 +0x308
runtime.(*mheap).alloc_m(0x6842a0, 0x1, 0x10, 0x0)
        c:/go/src/runtime/mheap.go:686 +0x126
runtime.(*mheap).alloc.func1()
        c:/go/src/runtime/mheap.go:753 +0x54
runtime.(*mheap).alloc(0x6842a0, 0x1, 0x10010, 0xc042032758)
        c:/go/src/runtime/mheap.go:752 +0x91
runtime.(*mcentral).grow(0x6859f0, 0x0)
        c:/go/src/runtime/mcentral.go:232 +0x9b
runtime.(*mcentral).cacheSpan(0x6859f0, 0x1f3)
        c:/go/src/runtime/mcentral.go:106 +0x2eb
runtime.(*mcache).refill(0x20506a8, 0xc04201c510)
        c:/go/src/runtime/mcache.go:123 +0xaa
runtime.(*mcache).nextFree.func1()
        c:/go/src/runtime/malloc.go:556 +0x39
runtime.systemstack(0x0)
        c:/go/src/runtime/asm_amd64.s:409 +0x7e
runtime.mstart()
        c:/go/src/runtime/proc.go:1175
```
The lua script is like this:
```
echo(true)
if spawn([[d:\OpenSSH-Win64\sftp.exe]],"-oBatchMode=no user@sftp.example.com") then
    expect("password:")
    echo(false)
    send("password\r")
    expect("sftp>")
    echo(true)
    send("put somebigfile.mp4 && exit\r")
end
```
System: Windows 7 PRO

**Comment by hymkor** [comment]
I could not reproduce the crash you reported, but I want to solve this issue.

Some question:

- Which version did you download and use ?
   - expect-20180808-386.zip 
   - expect-20180808-amd64.zip

- Does the error occur **on** `spawn` or **before** `spawn` ? With the script below , is `START` printed ?

```lua
echo(true)
echo("START")
if spawn([[d:\OpenSSH-Win64\sftp.exe]],"-oBatchMode=no user@sftp.example.com") then
   ----
end
```

- Does `spawn([[SOME-OTHER-EXECUTABLE]])` also crash ?

( Golang runtime may have a problem (bug?). I will rebuild expect.exe with the last version of golang after. )

**Comment by hymkor** [comment]
expect.exe of `expect-20180808-*****.zip` is built with Go 1.10.

I rebuild expect.exe with Go 1.11 .
https://github.com/zetamatta/expect/releases/tag/20180828

Would you try this version ?

**Comment by Jan-E** [comment]
I tried both the x86 and x64 versions. Both gave a memory error. And that was the same when I tried the 64-bits version to launch the 32-bits sftp.exe.

The red "start" did not appear when it was followed by the spawn statement (output buffering?), but appeared when there were no further statements afterwards or the spawn of another, small executable.

The good news: the new version worked. Screenshot:

![sftp](https://user-images.githubusercontent.com/1757825/44767916-e199dc80-ab5f-11e8-93aa-146700d3aa29.png)

Thanks for this awesome project!

**Comment by hymkor** [comment]
Thank you for report !

I am glad that the new version works as we expected.
Some issues are found on search with 'VirtualAlloc  errno=1455' on [golang's github](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=VirtualAlloc++errno%3D1455).
One of them may causes this trouble.

I hope that `expect.exe` will continue to be useful for you.

**Comment by Jan-E** [comment]
Just a tiny question: is there a way to suppress the commandline (the green part) without suppressing its output?

**Comment by hymkor** [comment]
With replacing `echo(true)`  to  `echo(false)` , expect.exe stops to output.

**Comment by Jan-E** [comment]
I see it now. Expect stops to output its colourful statements, but the white output in the console is never suppressed.

**Comment by Jan-E** [comment]
OK, closing. Thanks for the speedy response. I will recommend this program if anyone searches for scripting solutions on Windows.

**Comment by hymkor** [comment]
The white output in the console can not be suppressed.
Because they are output by spawned processes and `expect.exe`(expect() function) watchs the windows console-buffer directly.

If they are suppressed, the `expect()` function can not find keyword.

The output of process are not redirected because some program buffers their standard-output, and when their output are redirected, not CRLF terminated output (for example `Password:`) are never output and expect() waits keyword forever.

**Comment by Jan-E** [comment]
The screenshot above was made with the following expect.lua. It includes a nice example of branching, in case the sftp-server was not yet in the known_hosts list of the user.
```
echo(true)
echo("start")
if spawn([[d:\OpenSSH-Win64\sftp.exe]],"1@sftp.example.com") then
    -- The authenticity of host 'sftp.example.com' can't be established.
    -- RSA key fingerprint is SHA256:somekey
    -- Are you sure you want to continue connecting (yes/no)?
    -- Language independent check
    rc = expect("password:","SHA256:")
    if (rc == 1) then
        -- Store host key in C:\Users\<user>\.ssh\known_hosts
        echo(true)
        -- Dutch
        send("ja\r")
        rc = expect("password:","Please type 'yes' or 'no':")
        if (rc == 1) then
            -- English
            send("yes\r")
            rc = expect("password:")
        end
        -- Warning: Permanently added 'sftp.example.com' (RSA) to the list of known hosts.
    end
    echo(false)
    send("password\r")
    echo(true)
    expect("sftp>")
    send("put " .. arg[1] .. "\r")
    expect("sftp>")
    send("exit\r")
end
```
