### ISSUE TITLE
How can use it in Linux

### ISSUE THREAD

**Issue by zxbu** [hymkor/expect#9]
I use it in windows for a long time.   
Now I work in Linux enviroment , there is a  error  when I build expect.go by myself. 
```bash
➜  go build expect.go
go build github.com/zetamatta/go-console/screenbuffer: build constraints exclude all Go files in /root/go/src/github.com/zetamatta/go-console/screenbuffer
# github.com/zetamatta/go-console
/root/go/src/github.com/zetamatta/go-console/handle.go:38:15: undefined: syscall.Handle
/root/go/src/github.com/zetamatta/go-console/handle.go:40:16: undefined: syscall.NewLazyDLL
```

Ignore my poor English, Thanks

**Comment by hymkor** [comment]
Thank you for using expect.exe

It does not support Linux as platform because it reads console data with Windows native API by syscall library. I recommend the original Linux version of `expect`.
https://linux.die.net/man/1/expect .

**Comment by zxbu** [comment]
@zetamatta 
Thank you for your reply
